apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: kubeflow-user-example-com
  annotations:
    serving.kserve.io/s3-endpoint: minio.ns-1.svc.cluster.local
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: "us-east-1"
    serving.kserve.io/s3-useanoncredential: "false"
type: Opaque
stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
  AWS_ACCESS_KEY_ID: kubeflow
  AWS_SECRET_ACCESS_KEY: kubeflow123
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: kubeflow-user-example-com
secrets:
  - name: mysecret
---
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sentiment-analysis-model"
  namespace: kubeflow-user-example-com
spec:
  predictor:
    serviceAccountName: sa
    tensorflow:
      storageUri: "s3://datasets/imdb_sentiment_analysis"